project_id = "htvvpdwvzfbrodorujiy"

[functions.search-movies]
verify_jwt = false

[functions.trending-tmdb]
verify_jwt = false

[functions.trending-sports]
verify_jwt = false

[functions.trending-apps]
verify_jwt = false
